export let GameSettings = {
    ROUNDS: 10,
    EASY_MAXGAMEPOINTS: 2000,
    EASY_MAXDISTANCE: 100,
    MEDIUM_MAXGAMEPOINTS:  2500,
    MEDIUM_MAXDISTANCE: 100,
    HARD_MAXGAMEPOINTS: 3000,
    HARD_MAXDISTANCE: 25,
}